/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_daskks_ffmpeg_jniproxy_FFmpegJni */

#ifndef _Included_com_daskks_ffmpeg_jniproxy_FFmpegJni
#define _Included_com_daskks_ffmpeg_jniproxy_FFmpegJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_daskks_ffmpeg_jniproxy_FFmpegJni
 * Method:    onInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_daskks_ffmpeg_jniproxy_FFmpegJni_onInit
        (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_daskks_ffmpeg_jniproxvideo_decodey_FFmpegJni
 * Method:    onUnInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_daskks_ffmpeg_jniproxy_FFmpegJni_onUnInit
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL
Java_com_daskks_ffmpeg_MainActivity_video_1decode(JNIEnv *env, jobject instance, jstring input_,
                                                  jstring output_);

#ifdef __cplusplus
}
#endif


#endif